### ISSUE TITLE
Embeds don't have color and clinic legends

### ISSUE THREAD

**Issue by markwhiting** [Watts-Lab/COVID-Dashboard#11]
Can we add them in with the current embedding approach? Or is that super tricky?

**Comment by 3hoursofsleep** [comment]
I tried the fix we talked about (placing the legend and map in one observable html module before embedding it). For some reason, the styling for leaflet completely breaks and I have found no reason as to why. It looks like I might need to create a legend within the leaflet module.

**Comment by markwhiting** [comment]
OK. Strange. I guess just putting that in a less used corner would work. It could certainly be smaller than the ones we have on Observable.

**Comment by markwhiting** [comment]
Any update on this?
