### ISSUE TITLE
Show CT toggle has inconsistent behavior on CT dashboard

### ISSUE THREAD

**Issue by markwhiting** [Watts-Lab/COVID-Dashboard#12]
It looks like the show low pop ct's state is not observed when enabling and disabling show CTs. 

I think what I'd expect here is that those are independent toggles so they don't influence each others state and what is presented in the map is always at deference to the states the are currently on.

**Comment by 3hoursofsleep** [comment]
Removed "Hide low pop CTs" button.
Instead, just removed all no pop CTs by default.
