### ISSUE TITLE
Select bottom n% CTs does not observe low pop CT state in CT dashboard

### ISSUE THREAD

**Issue by markwhiting** [Watts-Lab/COVID-Dashboard#13]
If you select bottom n% on a variable that would include the low pop CTs they show even when low pop CTs are disabled with the toggle for that. 

I think what should happen is that the low pop state should dominate and nothing should be selected that is within that group if it's disabled.

**Comment by 3hoursofsleep** [comment]
Removed "Hide low pop CTs" button.
Instead, just removed all no pop CTs by default.
